// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgHvTw0zLXx5-Ma0VkiCq93CzvsauaQwk',
    appId: '1:531023136264:web:674c61d45e1e0bfe7933bd',
    messagingSenderId: '531023136264',
    projectId: 'ditonton-e9097',
    authDomain: 'ditonton-e9097.firebaseapp.com',
    storageBucket: 'ditonton-e9097.appspot.com',
    measurementId: 'G-7C15CKJJ4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfEhAEhrOTdJkX7ramZCNNWugxE3sUkY8',
    appId: '1:531023136264:android:7febd48b32d807ba7933bd',
    messagingSenderId: '531023136264',
    projectId: 'ditonton-e9097',
    storageBucket: 'ditonton-e9097.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB13EF92-EBHyy45JAnTHilEtFksAcBs5g',
    appId: '1:531023136264:ios:f373af70be14a76c7933bd',
    messagingSenderId: '531023136264',
    projectId: 'ditonton-e9097',
    storageBucket: 'ditonton-e9097.appspot.com',
    iosBundleId: 'com.example.ditonton',
  );
}
